// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoggxijtowzzsugcnude.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvZ2d4aWp0b3d6enN1Z2NudWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjc5NzMsImV4cCI6MjA3MTk0Mzk3M30.eAuRuVY-xwpKSy7aZ8tvRes2c0R_b4CgB0xjJYtwyOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});