export type RoleId =
  | 'ml-engineer'
  | 'data-scientist'
  | 'ai-researcher'
  | 'data-engineer'
  | 'mlops-engineer'
  | 'nlp-engineer'
  | 'cv-engineer'
  | 'ai-product-manager'
  | 'ai-ethics'
  | 'llm-engineer';

export interface RoleData {
  id: RoleId;
  name: string;
  tagline: string;
  description: string;
  keySkills: string[];
  typicalTools: string[];
  salaryRange: { junior: { min: number; max: number }; mid: { min: number; max: number }; senior: { min: number; max: number }; lead: { min: number; max: number } };
  demandLevel: 'Very High' | 'High' | 'Medium-High' | 'Medium' | 'Growing';
  dayToDay: string[];
  careerProgression: string[];
  pros: string[];
  cons: string[];
  educationTypical: string;
  jobSearchSlug: string;
  relatedRoles: RoleId[];
}

export const ROLES: RoleData[] = [
  {
    id: 'ml-engineer',
    name: 'Machine Learning Engineer',
    tagline: 'Build and deploy production ML models at scale',
    description:
      'Machine Learning Engineers bridge the gap between data science experiments and robust, scalable production systems. You design, build, and maintain ML pipelines that serve predictions to millions of users.',
    keySkills: [
      'Python',
      'TensorFlow / PyTorch',
      'MLOps & CI/CD',
      'Cloud Platforms (AWS/GCP/Azure)',
      'Software Engineering',
      'Data Pipelines',
      'Model Optimisation',
      'REST APIs',
    ],
    typicalTools: [
      'Python',
      'PyTorch',
      'TensorFlow',
      'Docker',
      'Kubernetes',
      'MLflow',
      'AWS SageMaker',
      'Git',
    ],
    salaryRange: {
      junior: { min: 80000, max: 110000 },
      mid: { min: 110000, max: 150000 },
      senior: { min: 140000, max: 190000 },
      lead: { min: 170000, max: 240000 },
    },
    demandLevel: 'Very High',
    dayToDay: [
      'Building and optimising ML model training pipelines',
      'Deploying models to production via APIs or batch systems',
      'Collaborating with data scientists on model handoff',
      'Monitoring model performance and retraining triggers',
      'Writing tests and documentation for ML systems',
    ],
    careerProgression: [
      'Junior ML Engineer',
      'ML Engineer',
      'Senior ML Engineer',
      'Staff ML Engineer',
      'Principal ML Engineer / ML Architect',
      'Head of ML Engineering',
    ],
    pros: [
      'Strong market demand across industries',
      'High salaries with consistent growth',
      'Tangible impact — your models serve real users',
      'Good balance of research and engineering',
    ],
    cons: [
      'Debugging production ML failures can be complex',
      'Need to stay current with fast-moving tooling',
      'Can involve significant infrastructure work',
      'On-call responsibilities for production models',
    ],
    educationTypical: 'Bachelor\'s or Master\'s in Computer Science, Software Engineering, or related field. Strong software engineering fundamentals are essential.',
    jobSearchSlug: 'machine learning engineer',
    relatedRoles: ['data-scientist', 'mlops-engineer', 'llm-engineer'],
  },
  {
    id: 'data-scientist',
    name: 'Data Scientist',
    tagline: 'Uncover insights and build predictive models',
    description:
      'Data Scientists analyse complex datasets, build predictive models, and communicate findings to drive business decisions. The role spans statistics, machine learning, and data storytelling.',
    keySkills: [
      'Python / R',
      'Statistics & Probability',
      'SQL',
      'Machine Learning',
      'Data Visualisation',
      'Experiment Design (A/B Testing)',
      'Feature Engineering',
      'Communication & Storytelling',
    ],
    typicalTools: [
      'Python',
      'Jupyter Notebooks',
      'pandas',
      'scikit-learn',
      'SQL',
      'Tableau / Power BI',
      'Git',
      'Spark',
    ],
    salaryRange: {
      junior: { min: 75000, max: 105000 },
      mid: { min: 105000, max: 145000 },
      senior: { min: 135000, max: 185000 },
      lead: { min: 165000, max: 230000 },
    },
    demandLevel: 'High',
    dayToDay: [
      'Exploratory data analysis on new datasets',
      'Building and evaluating predictive models',
      'Designing and analysing A/B experiments',
      'Creating dashboards and presenting findings to stakeholders',
      'Collaborating with engineers on data pipelines and deployment',
    ],
    careerProgression: [
      'Junior Data Scientist',
      'Data Scientist',
      'Senior Data Scientist',
      'Lead Data Scientist',
      'Principal Data Scientist',
      'Head of Data Science / Chief Data Officer',
    ],
    pros: [
      'Broad skillset applicable across industries',
      'Strong business impact and visibility',
      'Creative problem-solving with data',
      'Good entry point into the AI field',
    ],
    cons: [
      'Can become siloed from engineering teams',
      '"Data Scientist" title varies wildly across companies',
      'May spend significant time on data cleaning',
      'Models don\'t always make it to production',
    ],
    educationTypical: 'Bachelor\'s or Master\'s in Statistics, Mathematics, Computer Science, or quantitative field. PhD common but not required.',
    jobSearchSlug: 'data scientist',
    relatedRoles: ['ml-engineer', 'data-engineer', 'ai-researcher'],
  },
  {
    id: 'ai-researcher',
    name: 'AI/ML Researcher',
    tagline: 'Push the boundaries of what AI can do',
    description:
      'AI/ML Researchers develop novel algorithms, run experiments, and publish findings. The role demands deep mathematical thinking, experimental rigour, and a passion for advancing the state of the art.',
    keySkills: [
      'Deep Learning',
      'Mathematics (Linear Algebra, Calculus, Optimisation)',
      'Research Methodology',
      'Academic Writing',
      'PyTorch',
      'Experiment Design',
      'Statistical Analysis',
      'Paper Review & Critique',
    ],
    typicalTools: [
      'PyTorch',
      'JAX',
      'LaTeX',
      'Weights & Biases',
      'Jupyter Notebooks',
      'Git',
      'HPC / GPU Clusters',
      'arXiv',
    ],
    salaryRange: {
      junior: { min: 85000, max: 115000 },
      mid: { min: 115000, max: 155000 },
      senior: { min: 150000, max: 200000 },
      lead: { min: 180000, max: 260000 },
    },
    demandLevel: 'Medium',
    dayToDay: [
      'Reading and reviewing recent research papers',
      'Designing and running experiments',
      'Analysing results and iterating on hypotheses',
      'Writing papers and preparing conference submissions',
      'Collaborating with engineering teams on research-to-production transfer',
    ],
    careerProgression: [
      'Research Intern / Junior Researcher',
      'Research Scientist',
      'Senior Research Scientist',
      'Staff Research Scientist',
      'Principal Researcher',
      'Research Director / Chief Scientist',
    ],
    pros: [
      'Intellectually stimulating, cutting-edge work',
      'Opportunity to publish and build reputation',
      'High ceiling for compensation at top labs',
      'Influence the direction of the entire field',
    ],
    cons: [
      'Fewer positions available in Australia',
      'PhD often required for entry',
      'Research may not always have immediate business impact',
      'Can be isolating without a strong research team',
    ],
    educationTypical: 'PhD in Machine Learning, Computer Science, Mathematics, or related field is strongly preferred. Publications are a key differentiator.',
    jobSearchSlug: 'AI researcher',
    relatedRoles: ['data-scientist', 'nlp-engineer', 'cv-engineer'],
  },
  {
    id: 'data-engineer',
    name: 'Data Engineer',
    tagline: 'Design the infrastructure that powers AI',
    description:
      'Data Engineers design and maintain the data infrastructure that underpins AI and analytics. You build reliable pipelines, data warehouses, and ensure data quality at scale.',
    keySkills: [
      'SQL & Data Modelling',
      'Spark / Airflow',
      'Cloud Data Services',
      'Python',
      'ETL / ELT Design',
      'Data Warehousing',
      'Streaming (Kafka)',
      'Data Governance',
    ],
    typicalTools: [
      'SQL',
      'Python',
      'Apache Spark',
      'Apache Airflow',
      'dbt',
      'Snowflake / BigQuery / Redshift',
      'Kafka',
      'Terraform',
    ],
    salaryRange: {
      junior: { min: 75000, max: 100000 },
      mid: { min: 100000, max: 140000 },
      senior: { min: 130000, max: 180000 },
      lead: { min: 160000, max: 220000 },
    },
    demandLevel: 'Very High',
    dayToDay: [
      'Building and maintaining data pipelines and ETL jobs',
      'Designing data models and warehouse schemas',
      'Ensuring data quality through validation and monitoring',
      'Optimising query performance and pipeline reliability',
      'Collaborating with data scientists on data access and feature stores',
    ],
    careerProgression: [
      'Junior Data Engineer',
      'Data Engineer',
      'Senior Data Engineer',
      'Lead Data Engineer',
      'Staff Data Engineer / Data Architect',
      'Head of Data Engineering',
    ],
    pros: [
      'Extremely strong job security — every company needs data infrastructure',
      'Clear, well-defined engineering practices',
      'Transferable skills across industries',
      'Foundation for moving into ML Engineering or Architecture',
    ],
    cons: [
      'Less direct involvement with ML models',
      'Pipeline maintenance can be repetitive',
      'Often on-call for data pipeline failures',
      'May be seen as "supporting" rather than "building" AI',
    ],
    educationTypical: 'Bachelor\'s in Computer Science, Software Engineering, or related field. Practical experience with data systems often valued over advanced degrees.',
    jobSearchSlug: 'data engineer',
    relatedRoles: ['mlops-engineer', 'ml-engineer', 'data-scientist'],
  },
  {
    id: 'mlops-engineer',
    name: 'MLOps Engineer',
    tagline: 'Keep ML systems running smoothly in production',
    description:
      'MLOps Engineers operationalise machine learning by building CI/CD pipelines for models, automating training and deployment workflows, and monitoring model performance in production.',
    keySkills: [
      'Docker / Kubernetes',
      'CI/CD Pipelines',
      'Cloud Platforms',
      'Python',
      'Monitoring & Observability',
      'Infrastructure as Code',
      'Model Serving',
      'Linux / Networking',
    ],
    typicalTools: [
      'Docker',
      'Kubernetes',
      'Terraform',
      'GitHub Actions / Jenkins',
      'MLflow',
      'Prometheus / Grafana',
      'AWS / GCP / Azure',
      'Seldon / BentoML',
    ],
    salaryRange: {
      junior: { min: 80000, max: 110000 },
      mid: { min: 110000, max: 150000 },
      senior: { min: 140000, max: 190000 },
      lead: { min: 170000, max: 235000 },
    },
    demandLevel: 'High',
    dayToDay: [
      'Building automated model training and deployment pipelines',
      'Setting up monitoring and alerting for model drift',
      'Managing infrastructure for model serving (GPUs, clusters)',
      'Collaborating with ML Engineers on production readiness',
      'Improving reliability and reducing deployment friction',
    ],
    careerProgression: [
      'Junior MLOps Engineer',
      'MLOps Engineer',
      'Senior MLOps Engineer',
      'Lead MLOps Engineer',
      'Staff MLOps Engineer / ML Platform Lead',
      'Head of ML Platform / Infrastructure',
    ],
    pros: [
      'Rapidly growing field with increasing demand',
      'Critical role — every ML team needs MLOps eventually',
      'Strong overlap with DevOps (transferable skills)',
      'High impact on team productivity',
    ],
    cons: [
      'Tooling landscape changes very quickly',
      'Can be under-appreciated until something breaks',
      'Heavy on-call and operational responsibilities',
      'Less direct involvement with model development',
    ],
    educationTypical: 'Bachelor\'s in Computer Science, Software Engineering, or related field. DevOps or SRE background is a strong entry path.',
    jobSearchSlug: 'MLOps engineer',
    relatedRoles: ['ml-engineer', 'data-engineer', 'llm-engineer'],
  },
  {
    id: 'nlp-engineer',
    name: 'NLP Engineer',
    tagline: 'Make machines understand human language',
    description:
      'NLP Engineers specialise in building systems that process, understand, and generate human language. From sentiment analysis to machine translation, you work at the intersection of linguistics and deep learning.',
    keySkills: [
      'Transformers & Attention Mechanisms',
      'Python',
      'NLP Libraries (spaCy, Hugging Face)',
      'Deep Learning',
      'Linguistics Fundamentals',
      'Text Preprocessing',
      'Fine-tuning & Transfer Learning',
      'Evaluation Metrics (BLEU, ROUGE)',
    ],
    typicalTools: [
      'Hugging Face Transformers',
      'spaCy',
      'PyTorch',
      'NLTK',
      'Python',
      'Weights & Biases',
      'Docker',
      'FastAPI',
    ],
    salaryRange: {
      junior: { min: 85000, max: 115000 },
      mid: { min: 115000, max: 155000 },
      senior: { min: 145000, max: 195000 },
      lead: { min: 175000, max: 240000 },
    },
    demandLevel: 'High',
    dayToDay: [
      'Fine-tuning language models for specific tasks',
      'Building text classification, NER, or summarisation pipelines',
      'Evaluating model outputs against quality benchmarks',
      'Preprocessing and curating text datasets',
      'Collaborating with product teams on language features',
    ],
    careerProgression: [
      'Junior NLP Engineer',
      'NLP Engineer',
      'Senior NLP Engineer',
      'Lead NLP Engineer',
      'Principal NLP Engineer',
      'Head of NLP / Language AI',
    ],
    pros: [
      'LLM revolution has massively increased demand',
      'Fascinating intersection of language and technology',
      'Highly specialised — commands premium salaries',
      'Strong pathway into LLM Engineering',
    ],
    cons: [
      'Rapid pace of change (models obsolete quickly)',
      'Smaller talent pool can mean less mentorship',
      'Evaluation of language outputs is subjective',
      'Compute costs for training can be prohibitive',
    ],
    educationTypical: 'Master\'s or PhD in Computational Linguistics, NLP, or Computer Science. Strong background in both linguistics and deep learning is ideal.',
    jobSearchSlug: 'NLP engineer',
    relatedRoles: ['llm-engineer', 'ai-researcher', 'ml-engineer'],
  },
  {
    id: 'cv-engineer',
    name: 'Computer Vision Engineer',
    tagline: 'Teach computers to see and understand images',
    description:
      'Computer Vision Engineers build systems that interpret visual information — from object detection and image segmentation to medical imaging and autonomous vehicles.',
    keySkills: [
      'OpenCV',
      'Deep Learning (CNNs, Vision Transformers)',
      'Python',
      'Image Processing',
      'GPU Programming (CUDA)',
      'Object Detection (YOLO, Detectron)',
      'Data Augmentation',
      'Edge Deployment',
    ],
    typicalTools: [
      'OpenCV',
      'PyTorch',
      'TensorFlow',
      'CUDA',
      'Python',
      'Label Studio',
      'Docker',
      'ONNX Runtime',
    ],
    salaryRange: {
      junior: { min: 80000, max: 110000 },
      mid: { min: 110000, max: 150000 },
      senior: { min: 145000, max: 195000 },
      lead: { min: 175000, max: 235000 },
    },
    demandLevel: 'Medium-High',
    dayToDay: [
      'Training and fine-tuning object detection or segmentation models',
      'Building image processing and annotation pipelines',
      'Optimising models for real-time or edge deployment',
      'Evaluating model accuracy on custom datasets',
      'Collaborating with hardware teams on camera/sensor integration',
    ],
    careerProgression: [
      'Junior CV Engineer',
      'Computer Vision Engineer',
      'Senior CV Engineer',
      'Lead CV Engineer',
      'Principal CV Engineer',
      'Head of Computer Vision',
    ],
    pros: [
      'Visually rewarding — you can literally see your models work',
      'Strong demand in defence, mining, healthcare, and agriculture in Australia',
      'Niche expertise commands premium compensation',
      'Opportunity to work on cutting-edge hardware',
    ],
    cons: [
      'Data labelling is labour-intensive and expensive',
      'GPU costs can be significant',
      'Fewer pure CV roles compared to general ML',
      'Edge deployment adds hardware complexity',
    ],
    educationTypical: 'Master\'s or PhD in Computer Vision, Robotics, or Computer Science. Strong mathematical foundations in linear algebra and signal processing.',
    jobSearchSlug: 'computer vision engineer',
    relatedRoles: ['ml-engineer', 'ai-researcher', 'nlp-engineer'],
  },
  {
    id: 'ai-product-manager',
    name: 'AI Product Manager',
    tagline: 'Lead strategy for AI-powered products',
    description:
      'AI Product Managers lead the strategy and development of AI-powered products. You translate business needs into technical requirements and guide cross-functional teams to deliver impactful AI solutions.',
    keySkills: [
      'Product Strategy & Roadmapping',
      'Stakeholder Management',
      'AI/ML Literacy',
      'Agile / Scrum',
      'Data Analysis',
      'User Research',
      'Business Case Development',
      'Technical Communication',
    ],
    typicalTools: [
      'Jira / Linear',
      'Figma',
      'SQL',
      'Mixpanel / Amplitude',
      'Notion / Confluence',
      'Miro',
      'Google Analytics',
      'Slack',
    ],
    salaryRange: {
      junior: { min: 90000, max: 120000 },
      mid: { min: 120000, max: 155000 },
      senior: { min: 150000, max: 190000 },
      lead: { min: 180000, max: 220000 },
    },
    demandLevel: 'Medium-High',
    dayToDay: [
      'Defining product requirements and success metrics for AI features',
      'Prioritising the ML roadmap with engineering and data science',
      'Running user research and analysing product analytics',
      'Communicating AI capabilities and limitations to stakeholders',
      'Managing the trade-offs between model accuracy, speed, and cost',
    ],
    careerProgression: [
      'Associate Product Manager',
      'Product Manager (AI/ML)',
      'Senior Product Manager',
      'Group Product Manager',
      'Director of Product (AI)',
      'VP of Product / Chief Product Officer',
    ],
    pros: [
      'High visibility and business impact',
      'Bridge between technical and business worlds',
      'Growing demand as more companies adopt AI',
      'Strong pathway to executive leadership',
    ],
    cons: [
      'Need enough technical depth to challenge engineers',
      'Responsibility without direct control over implementation',
      'AI product timelines are harder to predict',
      'Explaining AI limitations to stakeholders can be frustrating',
    ],
    educationTypical: 'Bachelor\'s in any field; MBA or technical degree is a plus. Mix of product management experience and AI/ML literacy is key.',
    jobSearchSlug: 'AI product manager',
    relatedRoles: ['ai-ethics', 'data-scientist', 'ml-engineer'],
  },
  {
    id: 'ai-ethics',
    name: 'AI Ethics & Governance Specialist',
    tagline: 'Ensure AI is fair, transparent, and responsible',
    description:
      'AI Ethics & Governance Specialists ensure AI systems are fair, transparent, and compliant. You develop governance frameworks, audit algorithms for bias, and shape organisational AI policies aligned with Australian and international standards.',
    keySkills: [
      'AI Governance Frameworks',
      'Risk Assessment',
      'Policy Development',
      'Bias Auditing & Fairness Testing',
      'Stakeholder Engagement',
      'Regulatory Knowledge (AU AI Ethics Principles, EU AI Act)',
      'Technical AI/ML Literacy',
      'Report Writing & Communication',
    ],
    typicalTools: [
      'Fairlearn',
      'AI Verify',
      'Risk Assessment Templates',
      'Policy Documents',
      'Excel / Google Sheets',
      'Confluence / Notion',
      'Python (for auditing)',
      'Stakeholder Workshop Tools',
    ],
    salaryRange: {
      junior: { min: 80000, max: 110000 },
      mid: { min: 110000, max: 145000 },
      senior: { min: 140000, max: 180000 },
      lead: { min: 165000, max: 200000 },
    },
    demandLevel: 'Growing',
    dayToDay: [
      'Reviewing AI systems for bias, fairness, and compliance',
      'Developing and updating AI governance policies',
      'Running risk assessments on new AI deployments',
      'Advising product and engineering teams on responsible AI practices',
      'Staying current with regulatory changes and industry standards',
    ],
    careerProgression: [
      'AI Ethics Analyst',
      'AI Governance Specialist',
      'Senior AI Ethics Specialist',
      'AI Ethics Lead',
      'Head of Responsible AI',
      'Chief Ethics Officer / VP of Trust & Safety',
    ],
    pros: [
      'Rapidly growing field with increasing regulatory pressure',
      'Meaningful work with real societal impact',
      'Unique niche with less competition',
      'Strong in government and large enterprise sectors in Australia',
    ],
    cons: [
      'Field is still maturing — role scope varies widely',
      'Can be seen as a "blocker" by engineering teams',
      'Fewer positions compared to technical roles',
      'Requires continuous learning across policy and technology',
    ],
    educationTypical: 'Varied — Law, Philosophy, Public Policy, or Computer Science backgrounds are all common. Combination of technical literacy and policy expertise is ideal.',
    jobSearchSlug: 'AI ethics governance',
    relatedRoles: ['ai-product-manager', 'data-scientist', 'llm-engineer'],
  },
  {
    id: 'llm-engineer',
    name: 'Conversational AI / LLM Engineer',
    tagline: 'Build the next generation of intelligent applications',
    description:
      'LLM Engineers build applications powered by large language models. From RAG pipelines to AI agents, you design and deploy intelligent conversational systems that leverage foundation models.',
    keySkills: [
      'LLM APIs (OpenAI, Anthropic, etc.)',
      'Prompt Engineering',
      'RAG (Retrieval-Augmented Generation)',
      'LangChain / LlamaIndex',
      'Python',
      'Vector Databases',
      'Fine-tuning',
      'Evaluation & Safety',
    ],
    typicalTools: [
      'Python',
      'LangChain / LlamaIndex',
      'OpenAI API / Anthropic API',
      'Pinecone / Weaviate / ChromaDB',
      'FastAPI',
      'Docker',
      'Streamlit / Gradio',
      'Git',
    ],
    salaryRange: {
      junior: { min: 85000, max: 115000 },
      mid: { min: 115000, max: 160000 },
      senior: { min: 150000, max: 200000 },
      lead: { min: 180000, max: 250000 },
    },
    demandLevel: 'Very High',
    dayToDay: [
      'Building and refining RAG pipelines and prompt chains',
      'Integrating LLM APIs into production applications',
      'Evaluating model outputs for accuracy, safety, and cost',
      'Experimenting with different models and prompting strategies',
      'Building AI agents and multi-step reasoning systems',
    ],
    careerProgression: [
      'Junior LLM Engineer',
      'LLM Engineer',
      'Senior LLM Engineer',
      'Lead LLM Engineer',
      'Principal LLM / AI Engineer',
      'Head of AI Engineering',
    ],
    pros: [
      'Hottest area in AI — maximum demand right now',
      'Rapid innovation and exciting new capabilities',
      'Lower barrier to entry than traditional ML research',
      'Highly visible, product-facing work',
    ],
    cons: [
      'Field moves extremely fast — today\'s best practice is tomorrow\'s legacy',
      'LLM outputs are non-deterministic (harder to test)',
      'Vendor lock-in and API cost management challenges',
      'Risk of hype cycle — long-term demand unclear vs current peak',
    ],
    educationTypical: 'Bachelor\'s or Master\'s in Computer Science or related field. Practical experience with LLM APIs and building applications often matters more than academic credentials.',
    jobSearchSlug: 'LLM engineer',
    relatedRoles: ['nlp-engineer', 'ml-engineer', 'mlops-engineer'],
  },
];

export function getRoleById(id: RoleId): RoleData | undefined {
  return ROLES.find((r) => r.id === id);
}

export function getRoleNames(): { id: RoleId; name: string }[] {
  return ROLES.map((r) => ({ id: r.id, name: r.name }));
}
